### ISSUE TITLE
homebrew please

### ISSUE THREAD

**Issue by AlJohri** [jmhobbs/terminal-parrot#11]
hi, can you add this on homebrew please?

thanks!

![](http://cultofthepartyparrot.com/parrots/parrot.gif)

**Comment by jmhobbs** [comment]
I would be amazed if they accept it, but I can try.

**Comment by NathanTheGr8** [comment]
any world on this?
https://camo.githubusercontent.com/0de09ca17e02b8a50a0bf64b8be5a6274bd145e7/687474703a2f2f63756c746f667468657061727479706172726f742e636f6d2f706172726f74732f706172726f742e676966

**Comment by jmhobbs** [comment]
I didn't do anything about this actually 😨 

I'll read up on homebrew tonight and give it a shot, unless someone else is more saavy already.

**Comment by leggsimon** [comment]
Any luck?

**Comment by jmhobbs** [comment]
I don't believe that terminal-parrot qualifies for inclusion in homebrew, given their docs:

http://docs.brew.sh/Acceptable-Formulae.html

> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.
>
>We frown on authors submitting their own work unless it is very popular.

Perhaps we can find or create a tap that would accept the project though.

**Comment by jmhobbs** [comment]
I created a tap for this because ¯\\\_(シ)\_/¯ 

```
$ brew tap jmhobbs/parrot
==> Tapping jmhobbs/parrot
Cloning into '/usr/local/Homebrew/Library/Taps/jmhobbs/homebrew-parrot'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Tapped 1 formula (33 files, 25.2K)
$ brew install terminal-parrot
==> Installing terminal-parrot from jmhobbs/parrot
==> Downloading https://github.com/jmhobbs/terminal-parrot/archive/1.0.1.tar.gz
Already downloaded: /Users/johnhobbs/Library/Caches/Homebrew/terminal-parrot-1.0.1.tar.gz
==> go get -u github.com/nsf/termbox-go
==> go build -o parrot parrot.go draw.go data.go
🍺  /usr/local/Cellar/terminal-parrot/1.0.1: 4 files, 2.4M, built in 2 seconds
$ which parrot
/usr/local/bin/parrot
```
