### ISSUE TITLE
-delay and -orientation flags not working in terminal

### ISSUE THREAD

**Issue by hrousley** [jmhobbs/terminal-parrot#14]
Terminal V:2.5.3
Mac OS X 10.10.5
Installed via homebrew commands

`parrot` runs great
`parrot -orientation aussie` & `parrot -delay [int]` are kicking back errors

```
$ parrot -delay 25
flag provided but not defined: -delay
Usage of parrot:
  -loops int
    	number of times to loop (default: infinite)
$ parrot -orientation aussie
flag provided but not defined: -orientation
Usage of parrot:
  -loops int
    	number of times to loop (default: infinite)
```

**Comment by jmhobbs** [comment]
Whoops!  The release used in that tap doesn't include those flags.  I'll add them quick.

**Comment by jmhobbs** [comment]
This should be updated!  You can update the tap and then upgrade terminal-parrot and it should work now.

```
$ brew update
$ brew upgrade terminal-parrot
```

**Comment by hrousley** [comment]
Thanks John!
