### ISSUE TITLE
Problem with homebrew installation on macOS Big Sur 11.2.2

### ISSUE THREAD

**Issue by manettifabrizio** [jmhobbs/terminal-parrot#22]
<img width="902" alt="Screenshot 2021-03-03 at 22 04 03" src="https://user-images.githubusercontent.com/42788484/109872197-618ee900-7c6c-11eb-97de-36e398f7aaca.png">

**Comment by jmhobbs** [comment]
Confirmed on Catalina 10.15.7 as well, so not version dependent.  I'll take a look!

**Comment by jmhobbs** [comment]
Should now be fixed by https://github.com/jmhobbs/homebrew-parrot/commit/0d68239eca3bcb05621a89f73d6c218987d44273

You'll have to update the tap with a `brew update` before installing.
It also bumps things to 1.1.1, which includes some fixes from #15 

Thanks!
