### ISSUE TITLE
mention of using `parrot` instructions

### ISSUE THREAD

**Issue by 2dareis2do** [jmhobbs/terminal-parrot#27]
When I install terminal parrot  via homebrew on mac, the instructions in the README do not mention how to run

e.g.

parrot

**Comment by jmhobbs** [comment]
Good point!  Added a note about that to the README, thanks!

**Comment by jmhobbs** [comment]
Also added some notes to the `brew install`

![Screenshot 2024-09-03 at 2 56 53 PM](https://github.com/user-attachments/assets/0b1d4163-a5d8-48b5-8ec7-66b9b19d842f)
