### ISSUE TITLE
Should stop partying when Control+C is hit

### ISSUE THREAD

**Issue by v-yarotsky** [jmhobbs/terminal-parrot#4]
Right now it seems like you actually have to `kill` the parrot to make it stop partying in your terminal.

**Comment by jmhobbs** [comment]
Hitting the escape key will stop it.  Otherwise you can specify the `-loops` command to limit time on screen.

i.e. `parrot -loops 5`

**Comment by jmhobbs** [comment]
There should probably be some documentation on this though, as well as catching CTRL-C, "q" and some other common "quit me" keys.
