### ISSUE TITLE
panics if not run in a tty

### ISSUE THREAD

**Issue by dgonyeo** [jmhobbs/terminal-parrot#7]
I wanted to create a telnet service for terminal-parrot (whereby a user would be presented with the parrot when they telnet to a machine), and terminal-parrot will panic if it is not run in a tty.

A simple way to see this behavior is to use `systemd-run`:

```
derek@proton ~> sudo systemd-run parrot --loops 5                           
Running as unit: run-r4f979625766c483fa68dafa4269b052c.service
derek@proton ~> journalctl -u run-r4f979625766c483fa68dafa4269b052c.service --no-pager
-- Logs begin at Sat 2016-04-02 09:46:39 PDT, end at Fri 2016-06-17 11:16:28 PDT. --
Jun 17 11:16:28 proton systemd[1]: Started /home/derek/go/bin/parrot --loops 5.
Jun 17 11:16:28 proton parrot[3671]: panic: open /dev/tty: no such device or address
Jun 17 11:16:28 proton parrot[3671]: goroutine 1 [running]:
Jun 17 11:16:28 proton parrot[3671]: panic(0x53e5c0, 0xc82000a300)
Jun 17 11:16:28 proton parrot[3671]:         /nix/store/vf8zf1hr51bc6q3pqqgw74dniqxj63qi-go-1.6/share/go/src/runtime/panic.go:464 +0x3e6
Jun 17 11:16:28 proton parrot[3671]: main.main()
Jun 17 11:16:28 proton parrot[3671]:         /home/derek/go/src/github.com/jmhobbs/terminal-parrot/parrot.go:13 +0xab
Jun 17 11:16:28 proton systemd[1]: run-r4f979625766c483fa68dafa4269b052c.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 17 11:16:28 proton systemd[1]: run-r4f979625766c483fa68dafa4269b052c.service: Unit entered failed state.
Jun 17 11:16:28 proton systemd[1]: run-r4f979625766c483fa68dafa4269b052c.service: Failed with result 'exit-code'.
```

**Comment by jmhobbs** [comment]
So, this uses termbox-go, which is TTY oriented, and I don't think we can decouple that.

However, I did create a branch which changes it's behavior if it's stdout is not a terminal, i.e. it's piped through `cat` or something.  That might be a starting point for the telnet service.

https://github.com/jmhobbs/terminal-parrot/tree/tty-detection

**Comment by dgonyeo** [comment]
Also if it helps, this is specifically what I'm trying to do. Put these files in `/etc/systemd/system` and `systemctl daemon-reload && systemctl start parrot.socket`, then `telnet localhost`.
```
derek@proton ~> ls parrot*
parrot@.service  parrot.socket
derek@proton ~> cat parrot.socket 
[Unit]
Description=The Parrot Insists

[Socket]
ListenStream=23
Accept=yes

[Install]
WantedBy=sockets.target
derek@proton ~> cat parrot@.service 
[Unit]
Description=Cult of the Party Parrot

[Service]
ExecStart=-/home/derek/go/bin/parrot
StandardInput=socket
```

**Comment by jmhobbs** [comment]
I don't have any current Linux boxes to play with systemd on, but this branch works with this little node server I wrote, so I assume you should be able to use it with systemd.

![termbox-parrot-telnet](https://cloud.githubusercontent.com/assets/115059/16166535/af2fb656-34b1-11e6-8378-ccfa4047f541.gif)

```javascript
var net = require('net'),
   util = require('util'),
  spawn = require('child_process').spawn;
 
net.createServer(function (socket) {
    console.log('New client:', socket.remoteAddress);

    var parrot = spawn('./parrot', ['-loops', '2']);

    parrot.stdout.on('data', function (data) {
      socket.write('\033[2J')
      socket.write(data);
    });

    parrot.on('exit', function (code) {
      socket.end()
    });
}).listen(8888);

console.log('Listening on 8888');
```

The only tweak is that I added an ANSI escape code between frames to clear the telnet session screen, `socket.write('\033[2J')` (I'm assuming the telnet host supports ANSI, which is a fairly safe assumption)

The relationship between telnet, TERM, ANSI, etc. is beyond me as I've never played with any of that stuff, sorry.

**Comment by dgonyeo** [comment]
I wasn't able to build your branch in linux, so I tweaked it:
https://github.com/dgonyeo/terminal-parrot/commit/4b0782f8285acca0048936f5251124d218c1d4f0

I was about to make a PR, but I can't get my parrot service to work (it just immediately exits), so I'm holding off on making the PR until I can verify that I've accomplished what I want.

**Comment by dgonyeo** [comment]
Whoops, figured it out. There was a bug in the non-tty logic. Incoming PR.

**Comment by jmhobbs** [comment]
I don't think so, we should look at reworking #16 so it can merge again.
